
dist:
	find . -name "vdt-config.ng2" -exec tar czf ../../{}.tar.gz {} \;
	find . -name "vdt-config.ngdata" -exec tar czf ../../{}.tar.gz {} \;
	tar czf ../../vdt-config.nggums.tar.gz vdt-config.nggums ../gbuild/gums.config 
