
dist:
	tar czf ../../vdt-config.ng2.tar.gz ../vdt-templates/vdt-config.ng2
	tar czf ../../vdt-config.ngdata.tar.gz ../vdt-templates/vdt-config.ngdata
	tar chzf ../../vdt-config.nggums.tar.gz ../vdt-templates/vdt-config.nggums ../vdt-templates/gums.config 
