all:
	chmod +x vdt-helper

install: all
	mkdir -p /usr/local/share/doc/vdt-helper
	cp vdt-config.example /usr/local/share/doc/vdt-helper
	mkdir -p /usr/local/sbin
	cp vdt-helper /usr/local/sbin/vdt-install-helper

