MAKE=make


dist:
	-cd SOURCES/scripts/vdt-helper/ && $(MAKE)
	-cd SOURCES/scripts/vdt-templates/ && $(MAKE)
	-cd SOURCES/scripts/gridpulse/ && $(MAKE)
	-cd SOURCES/scripts/gbuild/ && $(MAKE)
	-cd SOURCES/infosystems/MIP/source/ && $(MAKE)

