MAKE=make


dist:
	-cd SOURCES/scripts/vdt-helper/ && $(MAKE)
	-cd SOURCES/scripts/vdt-templates/ && $(MAKE)
	-cd SOURCES/scripts/gridpulse/ && $(MAKE)
	-cd SOURCES/scripts/gbuild/ && $(MAKE)
	-cd SOURCES/infosystems/apac_py/ && $(MAKE)
	-cd SOURCES/infosystems/apac_py-config/ && $(MAKE)
	-cd SOURCES/infosystems/globus-mip-config/ && $(MAKE)
	-cd SOURCES/infosystems/glue-schema/ && $(MAKE)
	-cd SOURCES/infosystems/mip/ && $(MAKE)

